//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magfa
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://magfa.com/soap/SOAPSmsQueue", ConfigurationName="Magfa.SoapSmsQueuableImplementation")]
    public interface SoapSmsQueuableImplementation
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getDetailedStatusesResponse> getDetailedStatusesAsync(Magfa.getDetailedStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getMessageStatusResponse> getMessageStatusAsync(Magfa.getMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getMessageIdResponse> getMessageIdAsync(Magfa.getMessageIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getMessageStatusesResponse> getMessageStatusesAsync(Magfa.getMessageStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getRealMessageStatusesResponse> getRealMessageStatusesAsync(Magfa.getRealMessageStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getAllMessagesWithNumberResponse> getAllMessagesWithNumberAsync(Magfa.getAllMessagesWithNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getMessagesWithNumberResponse> getMessagesWithNumberAsync(Magfa.getMessagesWithNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getCreditResponse> getCreditAsync(Magfa.getCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getAllMessagesResponse> getAllMessagesAsync(Magfa.getAllMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.getMessagesResponse> getMessagesAsync(Magfa.getMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.enqueueWithGatewayResponse> enqueueWithGatewayAsync(Magfa.enqueueWithGatewayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerReturnIncomingFormat))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeliveryStatus))]
        System.Threading.Tasks.Task<Magfa.enqueueResponse> enqueueAsync(Magfa.enqueueRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SOAPSmsQueue")]
    public partial class DeliveryStatus
    {
        
        private string dateField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(DatedCustomerReturnIncomingFormat))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SOAPSmsQueue")]
    public partial class CustomerReturnIncomingFormat
    {
        
        private string bodyField;
        
        private string errorResultField;
        
        private string recipientNumberField;
        
        private string senderNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorResult
        {
            get
            {
                return this.errorResultField;
            }
            set
            {
                this.errorResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recipientNumber
        {
            get
            {
                return this.recipientNumberField;
            }
            set
            {
                this.recipientNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string senderNumber
        {
            get
            {
                return this.senderNumberField;
            }
            set
            {
                this.senderNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SOAPSmsQueue")]
    public partial class DatedCustomerReturnIncomingFormat : CustomerReturnIncomingFormat
    {
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDetailedStatuses", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getDetailedStatusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long[] messagesId;
        
        public getDetailedStatusesRequest()
        {
        }
        
        public getDetailedStatusesRequest(string domain, long[] messagesId)
        {
            this.domain = domain;
            this.messagesId = messagesId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDetailedStatusesResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getDetailedStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Magfa.DeliveryStatus[] getDetailedStatusesReturn;
        
        public getDetailedStatusesResponse()
        {
        }
        
        public getDetailedStatusesResponse(Magfa.DeliveryStatus[] getDetailedStatusesReturn)
        {
            this.getDetailedStatusesReturn = getDetailedStatusesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessageStatus", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessageStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long messageId;
        
        public getMessageStatusRequest()
        {
        }
        
        public getMessageStatusRequest(long messageId)
        {
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessageStatusResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessageStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int getMessageStatusReturn;
        
        public getMessageStatusResponse()
        {
        }
        
        public getMessageStatusResponse(int getMessageStatusReturn)
        {
            this.getMessageStatusReturn = getMessageStatusReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessageId", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessageIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long checkingMessageId;
        
        public getMessageIdRequest()
        {
        }
        
        public getMessageIdRequest(string domain, long checkingMessageId)
        {
            this.domain = domain;
            this.checkingMessageId = checkingMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessageIdResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessageIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long getMessageIdReturn;
        
        public getMessageIdResponse()
        {
        }
        
        public getMessageIdResponse(long getMessageIdReturn)
        {
            this.getMessageIdReturn = getMessageIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessageStatuses", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessageStatusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] messagesId;
        
        public getMessageStatusesRequest()
        {
        }
        
        public getMessageStatusesRequest(long[] messagesId)
        {
            this.messagesId = messagesId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessageStatusesResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessageStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int[] getMessageStatusesReturn;
        
        public getMessageStatusesResponse()
        {
        }
        
        public getMessageStatusesResponse(int[] getMessageStatusesReturn)
        {
            this.getMessageStatusesReturn = getMessageStatusesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRealMessageStatuses", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getRealMessageStatusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] messagesId;
        
        public getRealMessageStatusesRequest()
        {
        }
        
        public getRealMessageStatusesRequest(long[] messagesId)
        {
            this.messagesId = messagesId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRealMessageStatusesResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getRealMessageStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int[] getRealMessageStatusesReturn;
        
        public getRealMessageStatusesResponse()
        {
        }
        
        public getRealMessageStatusesResponse(int[] getRealMessageStatusesReturn)
        {
            this.getRealMessageStatusesReturn = getRealMessageStatusesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllMessagesWithNumber", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getAllMessagesWithNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int numberOfMessages;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string destNumber;
        
        public getAllMessagesWithNumberRequest()
        {
        }
        
        public getAllMessagesWithNumberRequest(string domain, int numberOfMessages, string destNumber)
        {
            this.domain = domain;
            this.numberOfMessages = numberOfMessages;
            this.destNumber = destNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllMessagesWithNumberResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getAllMessagesWithNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object[] getAllMessagesWithNumberReturn;
        
        public getAllMessagesWithNumberResponse()
        {
        }
        
        public getAllMessagesWithNumberResponse(object[] getAllMessagesWithNumberReturn)
        {
            this.getAllMessagesWithNumberReturn = getAllMessagesWithNumberReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesWithNumber", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessagesWithNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int numberOfMessages;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string destNumber;
        
        public getMessagesWithNumberRequest()
        {
        }
        
        public getMessagesWithNumberRequest(string domain, int numberOfMessages, string destNumber)
        {
            this.domain = domain;
            this.numberOfMessages = numberOfMessages;
            this.destNumber = destNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesWithNumberResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessagesWithNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object[] getMessagesWithNumberReturn;
        
        public getMessagesWithNumberResponse()
        {
        }
        
        public getMessagesWithNumberResponse(object[] getMessagesWithNumberReturn)
        {
            this.getMessagesWithNumberReturn = getMessagesWithNumberReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCredit", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        public getCreditRequest()
        {
        }
        
        public getCreditRequest(string domain)
        {
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public float getCreditReturn;
        
        public getCreditResponse()
        {
        }
        
        public getCreditResponse(float getCreditReturn)
        {
            this.getCreditReturn = getCreditReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllMessages", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getAllMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int numberOfMessages;
        
        public getAllMessagesRequest()
        {
        }
        
        public getAllMessagesRequest(string domain, int numberOfMessages)
        {
            this.domain = domain;
            this.numberOfMessages = numberOfMessages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllMessagesResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getAllMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object[] getAllMessagesReturn;
        
        public getAllMessagesResponse()
        {
        }
        
        public getAllMessagesResponse(object[] getAllMessagesReturn)
        {
            this.getAllMessagesReturn = getAllMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessages", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int numberOfMessages;
        
        public getMessagesRequest()
        {
        }
        
        public getMessagesRequest(string domain, int numberOfMessages)
        {
            this.domain = domain;
            this.numberOfMessages = numberOfMessages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class getMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object[] getMessagesReturn;
        
        public getMessagesResponse()
        {
        }
        
        public getMessagesResponse(object[] getMessagesReturn)
        {
            this.getMessagesReturn = getMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enqueueWithGateway", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class enqueueWithGatewayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string[] messageBodies;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string[] recipientNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] senderNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int[] encodings;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] udhs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int[] messageClasses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int[] priorities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public long[] checkingMessageIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string gateway;
        
        public enqueueWithGatewayRequest()
        {
        }
        
        public enqueueWithGatewayRequest(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds, string gateway)
        {
            this.domain = domain;
            this.messageBodies = messageBodies;
            this.recipientNumbers = recipientNumbers;
            this.senderNumbers = senderNumbers;
            this.encodings = encodings;
            this.udhs = udhs;
            this.messageClasses = messageClasses;
            this.priorities = priorities;
            this.checkingMessageIds = checkingMessageIds;
            this.gateway = gateway;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enqueueWithGatewayResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class enqueueWithGatewayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] enqueueWithGatewayReturn;
        
        public enqueueWithGatewayResponse()
        {
        }
        
        public enqueueWithGatewayResponse(long[] enqueueWithGatewayReturn)
        {
            this.enqueueWithGatewayReturn = enqueueWithGatewayReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enqueue", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class enqueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string[] messageBodies;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string[] recipientNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] senderNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int[] encodings;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] udhs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int[] messageClasses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int[] priorities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public long[] checkingMessageIds;
        
        public enqueueRequest()
        {
        }
        
        public enqueueRequest(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds)
        {
            this.domain = domain;
            this.messageBodies = messageBodies;
            this.recipientNumbers = recipientNumbers;
            this.senderNumbers = senderNumbers;
            this.encodings = encodings;
            this.udhs = udhs;
            this.messageClasses = messageClasses;
            this.priorities = priorities;
            this.checkingMessageIds = checkingMessageIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enqueueResponse", WrapperNamespace="http://magfa.com/soap/SOAPSmsQueue", IsWrapped=true)]
    public partial class enqueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] enqueueReturn;
        
        public enqueueResponse()
        {
        }
        
        public enqueueResponse(long[] enqueueReturn)
        {
            this.enqueueReturn = enqueueReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SoapSmsQueuableImplementationChannel : Magfa.SoapSmsQueuableImplementation, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SoapSmsQueuableImplementationClient : System.ServiceModel.ClientBase<Magfa.SoapSmsQueuableImplementation>, Magfa.SoapSmsQueuableImplementation
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SoapSmsQueuableImplementationClient() : 
                base(SoapSmsQueuableImplementationClient.GetDefaultBinding(), SoapSmsQueuableImplementationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSmsQueuableImplementationClient(EndpointConfiguration endpointConfiguration) : 
                base(SoapSmsQueuableImplementationClient.GetBindingForEndpoint(endpointConfiguration), SoapSmsQueuableImplementationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSmsQueuableImplementationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SoapSmsQueuableImplementationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSmsQueuableImplementationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SoapSmsQueuableImplementationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSmsQueuableImplementationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Magfa.getDetailedStatusesResponse> getDetailedStatusesAsync(Magfa.getDetailedStatusesRequest request)
        {
            return base.Channel.getDetailedStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getMessageStatusResponse> getMessageStatusAsync(Magfa.getMessageStatusRequest request)
        {
            return base.Channel.getMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getMessageIdResponse> getMessageIdAsync(Magfa.getMessageIdRequest request)
        {
            return base.Channel.getMessageIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getMessageStatusesResponse> getMessageStatusesAsync(Magfa.getMessageStatusesRequest request)
        {
            return base.Channel.getMessageStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getRealMessageStatusesResponse> getRealMessageStatusesAsync(Magfa.getRealMessageStatusesRequest request)
        {
            return base.Channel.getRealMessageStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getAllMessagesWithNumberResponse> getAllMessagesWithNumberAsync(Magfa.getAllMessagesWithNumberRequest request)
        {
            return base.Channel.getAllMessagesWithNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getMessagesWithNumberResponse> getMessagesWithNumberAsync(Magfa.getMessagesWithNumberRequest request)
        {
            return base.Channel.getMessagesWithNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getCreditResponse> getCreditAsync(Magfa.getCreditRequest request)
        {
            return base.Channel.getCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getAllMessagesResponse> getAllMessagesAsync(Magfa.getAllMessagesRequest request)
        {
            return base.Channel.getAllMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.getMessagesResponse> getMessagesAsync(Magfa.getMessagesRequest request)
        {
            return base.Channel.getMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.enqueueWithGatewayResponse> enqueueWithGatewayAsync(Magfa.enqueueWithGatewayRequest request)
        {
            return base.Channel.enqueueWithGatewayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magfa.enqueueResponse> enqueueAsync(Magfa.enqueueRequest request)
        {
            return base.Channel.enqueueAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://sms.magfa.com/services/urn:SOAPSmsQueue");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SoapSmsQueuableImplementationClient.GetBindingForEndpoint(EndpointConfiguration.TSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SoapSmsQueuableImplementationClient.GetEndpointAddress(EndpointConfiguration.TSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            TSOAP,
        }
    }
}
